apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vymanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BryanR77/homelab-cluster-apps-values.git
    targetRevision: HEAD
    path: vymanager/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: vymanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
