apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patchmon
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/BryanR77/patchmon-helm.git
      targetRevision: main
      path: charts/patchmon
      helm:
        valueFiles:
          - $values/patchmon/values.yaml
    - repoURL: https://github.com/BryanR77/homelab-cluster-apps-values.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: patchmon
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
