apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: ghcr.io/go-vikunja/helm-chart
      chart: vikunja
      targetRevision: 2.2.1
      helm:
        valueFiles:
          - $values/vikunja/values.yaml
    - repoURL: https://github.com/BryanR77/homelab-cluster-apps-values.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BryanR77/homelab-cluster-apps-values.git
      targetRevision: HEAD
      path: vikunja/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: vikunja
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
